openapi: 3.0.3
info:
  title: Pulpod - OpenAPI 3.0
  contact:
    email: pabrodri@redhat.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Pulpod repository
  url: https://github.com/openstack-tooling/pulpod
paths:
  /plugins:
    get:
      tags:
        - plugin
      summary: Retrieves the list of loaded plugins
      description: Returns all the available loaded plugins
      operationId: listPlugins
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PluginMetadata'
        '400':
          description: Invalid status value

  /plugins/{pluginId}/subscription:
    post:
      tags:
        - plugin
      summary: Creates the subscription for the given plugin
      description: ''
      operationId: createSubscription
      parameters:
        - name: pluginId
          in: path
          description: ID of the plugin
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionCreationRequest'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
  /resources:
    get:
      tags:
        - resource
      summary: Retrieves all the existing resources
      description: |
        Returns all the available loaded plugins.
        If the exposed query parameters are given the result will be filtered out
      parameters:
        - name: type
          in: query
          description: Filters the results by type
          required: false
          explode: true
          schema:
            type: string
        - name: version
          in: query
          description: Filters the results by API version
          required: false
          explode: true
          schema:
            type: string
        - name: name
          in: query
          description: Filters the results by resource name
          required: false
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Resource"


components:
  schemas:
    PluginMetadata:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
    SubscriptionCreationRequest:
      type: object
      properties:
        webhookUrl:
          type: string
        watchedResources:
          type: array
          items: {
            "$ref": "#/components/schemas/ResourceSelector"
          }
    ResourceSelector:
      type: object
      properties:
        type:
          type: string
          example: InstanceRequest
        version:
          type: string
          example: v1
        name:
          type: string
          example: instance-request-1
    Resource:
      type: object
      properties:
        type:
          type: string
          example: InstanceRequest
        version:
          type: string
          example: v1
        name:
          type: string
          example: instance-request-1
        data:
          type: object
